// File generated by Antigravity for Firebase configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5EnlNN4K7McAsAev_-g3qcllTHc67GCg',
    appId: '1:727425292908:web:393807034d880028319649',
    messagingSenderId: '727425292908',
    projectId: 'scholars-c23e4',
    authDomain: 'scholars-c23e4.firebaseapp.com',
    databaseURL: 'https://scholars-c23e4-default-rtdb.firebaseio.com',
    storageBucket: 'scholars-c23e4.firebasestorage.app',
    measurementId: 'G-8WS0QXZCJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPJhZ8CSwMlUdN6CdtYU5A_4Eulhh2mnk',
    appId: '1:727425292908:android:b0eb69b7df48fce8319649',
    messagingSenderId: '727425292908',
    projectId: 'scholars-c23e4',
    databaseURL: 'https://scholars-c23e4-default-rtdb.firebaseio.com',
    storageBucket: 'scholars-c23e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJhZ8CSwMlUdN6CdtYU5A_4Eulhh2mnk',
    appId: '1:727425292908:ios:b0eb69b7df48fce8319649',
    messagingSenderId: '727425292908',
    projectId: 'scholars-c23e4',
    databaseURL: 'https://scholars-c23e4-default-rtdb.firebaseio.com',
    storageBucket: 'scholars-c23e4.firebasestorage.app',
    iosBundleId: 'com.academy.scholars',
  );
}
